spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studiomedicodb
    username: developer
    password: developer
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false
  output:
    ansi:
      enabled: always
    logging:
      level:
        root: INFO
